### ISSUE TITLE
Files not deployed to storage account

### ISSUE THREAD

**Issue by ralphke** [microsoft/ignite-learning-paths-training-data#1] opened 2020-02-13 07:43 UTC
Within the current deployment script, the data and logfiles are not deployed to the storage containers.
in my deployment the container data and log are empty after a successful deployment.

**Comment by amynic** [comment] 2020-02-21 11:23
Hi @ralphke It looks like the deployment script creates all infrastructure however at the bottom of this page: https://github.com/microsoft/ignite-learning-paths-training-data/blob/master/data10/deployment/README.md you have instructions to add data files via curl or bash commands - have you completed this step and still you see no files?

**Comment by ilikesql** [comment] 2020-02-21 11:39
This was fixed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amynic** [comment] 2020-02-21 11:51
Thanks @ilikesql - can you confirm what was fixed. I just tested the deploy to Azure template (infrastructure only) and then used cloud shell to copy the files to the storage account - this seems success - is this correct?

**Comment by ilikesql** [comment] 2020-02-21 14:02
As per the deployment script and manual including the curl script, folders are created and files are created, and you validated all services.
________________________________

**Comment by amynic** [comment] 2020-02-21 14:22
Ok confirmed and tested. Closing this issue

**Closed as completed by amynic** 2020-02-21 14:22 UTC
Labels: documentation, Session Setup
